/**
 * PDF Export — generates a multi-page PDF from OutputJSON
 * Uses jsPDF for document creation, jspdf-autotable for tables,
 * and svg2pdf.js for vector floor plan rendering.
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { OutputJSON } from '@/types';
import type { Project } from '@/types';
import { buildFloorPlanSVG } from './pdf/svg-builder';

const MARGIN = 20;
const PAGE_W = 279.4; // Letter width mm (landscape)
const PAGE_H = 215.9; // Letter height mm (landscape)
const PORTRAIT_W = 215.9;
const PORTRAIT_H = 279.4;
const HEADER_Y = 15;
const BODY_Y = 28;

function addHeader(doc: jsPDF, title: string, pageNum: number) {
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(title, MARGIN, HEADER_Y);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(120);
  doc.text(`Page ${pageNum}`, doc.internal.pageSize.getWidth() - MARGIN, HEADER_Y, { align: 'right' });
  doc.setTextColor(0);
  doc.setDrawColor(200);
  doc.line(MARGIN, HEADER_Y + 3, doc.internal.pageSize.getWidth() - MARGIN, HEADER_Y + 3);
}

function addFooter(doc: jsPDF) {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  doc.setFontSize(7);
  doc.setTextColor(160);
  doc.text('Generated by Archonek — AI-Powered Clinic Planning', MARGIN, h - 8);
  doc.text(new Date().toLocaleDateString('en-CA'), w - MARGIN, h - 8, { align: 'right' });
  doc.setTextColor(0);
}

export async function exportProjectPDF(output: OutputJSON, project: Project): Promise<Blob> {
  let pageNum = 0;

  // ── Page 1: Cover Sheet (Portrait) ──
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' });
  pageNum++;

  const cs = output.cover_sheet;
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text(cs?.project_name ?? `${project.clinic_type} Clinic`, MARGIN, 50);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  const infoLines = [
    `Address: ${cs?.address ?? project.city + ', ' + project.province}`,
    `Building Type: ${cs?.building_type ?? 'TBD'}`,
    `Total Area: ${(cs?.total_area_sqft ?? project.area_sqft).toLocaleString()} SF (${cs?.total_area_m2 ?? Math.round(project.area_sqft * 0.093)} m²)`,
    `Rooms: ${cs?.room_count ?? output.room_schedule?.length ?? '—'}`,
    `Owner: ${cs?.owner ?? 'TBD'}`,
    `Architect: ${cs?.architect ?? 'TBD'}`,
    `Date: ${cs?.date ?? new Date().toLocaleDateString('en-CA')}`,
  ];
  let y = 65;
  for (const line of infoLines) {
    doc.text(line, MARGIN, y);
    y += 7;
  }

  // Applicable codes
  if (cs?.applicable_codes?.length) {
    y += 5;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Applicable Codes:', MARGIN, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    for (const code of cs.applicable_codes) {
      doc.text(`• ${code}`, MARGIN + 4, y);
      y += 5;
    }
  }

  // Drawing index
  if (cs?.drawing_index?.length) {
    y += 8;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Drawing Index:', MARGIN, y);
    y += 2;
    autoTable(doc, {
      startY: y,
      margin: { left: MARGIN, right: MARGIN },
      head: [['No.', 'Title', 'Discipline']],
      body: cs.drawing_index.map(d => [d.drawing_number, d.title, d.discipline]),
      styles: { fontSize: 8 },
      headStyles: { fillColor: [68, 64, 60] },
    });
  }
  addFooter(doc);

  // ── Page 2: Floor Plan (Landscape) ──
  if (output.floor_plan) {
    doc.addPage('letter', 'landscape');
    pageNum++;
    addHeader(doc, 'A100 — Floor Plan', pageNum);

    const svgString = buildFloorPlanSVG(output);
    // Parse SVG and render via svg2pdf.js
    const parser = new DOMParser();
    const svgDoc = parser.parseFromString(svgString, 'image/svg+xml');
    const svgElement = svgDoc.documentElement;

    try {
      const { svg2pdf } = await import('svg2pdf.js');
      await svg2pdf(svgElement, doc, {
        x: MARGIN,
        y: BODY_Y,
        width: PAGE_W - MARGIN * 2,
        height: PAGE_H - BODY_Y - 15,
      });
    } catch {
      // Fallback: text note if svg2pdf fails
      doc.setFontSize(10);
      doc.text('Floor plan SVG rendering unavailable. See interactive viewer.', MARGIN, BODY_Y + 10);
    }
    addFooter(doc);
  }

  // ── Page 3: Reflected Ceiling Plan info ──
  if (output.ceiling_plan) {
    doc.addPage('letter', 'portrait');
    pageNum++;
    addHeader(doc, 'Reflected Ceiling Plan', pageNum);

    const cp = output.ceiling_plan;
    doc.setFontSize(9);
    doc.text(`Ceiling System: ${cp.ceiling_type === 'tbar' ? 'Suspended ACT (T-Bar)' : cp.ceiling_type}`, MARGIN, BODY_Y);
    doc.text(`Grid Module: ${cp.grid_module}`, MARGIN, BODY_Y + 5);

    autoTable(doc, {
      startY: BODY_Y + 12,
      margin: { left: MARGIN, right: MARGIN },
      head: [['Room', 'Ceiling', 'Height', 'Lights', 'Diffusers', 'Sprinklers']],
      body: cp.rooms.map(r => [
        `${r.room_number} ${r.room_name}`,
        r.ceiling_type === 'tbar' ? 'ACT' : r.ceiling_type === 'drywall' ? 'GWB' : 'Mixed',
        `${r.ceiling_height_ft}'`,
        String(r.light_fixtures.length),
        String(r.diffusers.length),
        String(r.sprinklers.length),
      ]),
      styles: { fontSize: 7 },
      headStyles: { fillColor: [68, 64, 60] },
    });
    addFooter(doc);
  }

  // ── Page 4: Room Schedule ──
  if (output.room_schedule?.length) {
    doc.addPage('letter', 'portrait');
    pageNum++;
    addHeader(doc, 'Room Schedule', pageNum);

    autoTable(doc, {
      startY: BODY_Y,
      margin: { left: MARGIN, right: MARGIN },
      head: [['No.', 'Room Name', 'Area (SF)', 'Area (m²)', 'Finish', 'Notes']],
      body: output.room_schedule.map(r => [
        r.room_number, r.room_name,
        String(r.area_sqft), String(r.area_m2),
        r.finish_code, r.notes.slice(0, 60),
      ]),
      styles: { fontSize: 7 },
      headStyles: { fillColor: [68, 64, 60] },
      columnStyles: { 5: { cellWidth: 50 } },
    });
    addFooter(doc);
  }

  // ── Page 5: Equipment Schedule ──
  if (output.equipment_schedule?.length) {
    doc.addPage('letter', 'landscape');
    pageNum++;
    addHeader(doc, 'Equipment Schedule', pageNum);

    autoTable(doc, {
      startY: BODY_Y,
      margin: { left: MARGIN, right: MARGIN },
      head: [['ID', 'Equipment', 'Room', 'Qty', 'HW', 'CW', 'DR', 'Gas', 'Ded.', 'Data', 'Vent']],
      body: output.equipment_schedule.map(eq => [
        eq.id, eq.name, eq.room, String(eq.quantity),
        eq.hot_water ? '•' : '', eq.cold_water ? '•' : '',
        eq.drain ? '•' : '', eq.gas ? '•' : '',
        eq.dedicated_circuit ? '•' : '', eq.data ? '•' : '',
        eq.mechanical_vent ? '•' : '',
      ]),
      styles: { fontSize: 7 },
      headStyles: { fillColor: [68, 64, 60] },
    });
    addFooter(doc);
  }

  // ── Page 6: Finishes & Wall Types ──
  if (output.finish_schedule?.length || output.wall_types?.length) {
    doc.addPage('letter', 'portrait');
    pageNum++;
    addHeader(doc, 'Finish Schedule & Wall Types', pageNum);

    let startY = BODY_Y;
    if (output.finish_schedule?.length) {
      autoTable(doc, {
        startY,
        margin: { left: MARGIN, right: MARGIN },
        head: [['Room', 'Code', 'Wall', 'Floor', 'Ceiling', 'Base']],
        body: output.finish_schedule.map(f => [
          f.room_name, f.finish_code, f.wall.slice(0, 30), f.floor.slice(0, 30),
          f.ceiling.slice(0, 25), f.base.slice(0, 20),
        ]),
        styles: { fontSize: 6.5 },
        headStyles: { fillColor: [68, 64, 60] },
      });
      startY = ((doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? startY + 70) + 10;
    }

    if (output.wall_types?.length) {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text('Wall Types', MARGIN, startY);
      autoTable(doc, {
        startY: startY + 3,
        margin: { left: MARGIN, right: MARGIN },
        head: [['Code', 'Description', 'Stud', 'Fire Rating', 'STC']],
        body: output.wall_types.map(w => [
          w.type_code, w.description, w.stud_size, w.fire_rating, String(w.stc_rating),
        ]),
        styles: { fontSize: 7 },
        headStyles: { fillColor: [68, 64, 60] },
      });
    }
    addFooter(doc);
  }

  // ── Page 7: Door Schedule ──
  if (output.door_schedule?.length) {
    doc.addPage('letter', 'portrait');
    pageNum++;
    addHeader(doc, 'Door Schedule', pageNum);

    autoTable(doc, {
      startY: BODY_Y,
      margin: { left: MARGIN, right: MARGIN },
      head: [['Mark', 'Location', 'Size (mm)', 'Type', 'Fire Rating', 'Hardware']],
      body: output.door_schedule.map(d => [
        d.mark, d.location, `${d.width_mm} × ${d.height_mm}`,
        d.type, d.fire_rating, d.hardware,
      ]),
      styles: { fontSize: 7 },
      headStyles: { fillColor: [68, 64, 60] },
    });
    addFooter(doc);
  }

  // ── Page 8: Compliance Checklist ──
  if (output.compliance_checklist?.length) {
    doc.addPage('letter', 'portrait');
    pageNum++;
    addHeader(doc, 'Compliance Checklist', pageNum);

    autoTable(doc, {
      startY: BODY_Y,
      margin: { left: MARGIN, right: MARGIN },
      head: [['Category', 'Requirement', 'Code Ref', 'Status']],
      body: output.compliance_checklist.map(c => [
        c.category, c.requirement, c.code_reference,
        c.status === 'met' ? 'MET' : c.status === 'review' ? 'REVIEW' : 'ACTION',
      ]),
      styles: { fontSize: 7 },
      headStyles: { fillColor: [68, 64, 60] },
      bodyStyles: {},
      didParseCell: (data) => {
        if (data.section === 'body' && data.column.index === 3) {
          const val = (data.row.raw as string[])[3];
          if (val === 'ACTION') data.cell.styles.textColor = [185, 28, 28];
          else if (val === 'REVIEW') data.cell.styles.textColor = [180, 130, 0];
          else data.cell.styles.textColor = [22, 163, 74];
        }
      },
    });
    addFooter(doc);
  }

  // ── Page 9: Scope of Work + Next Steps ──
  if (output.scope_of_work?.length || output.next_steps?.length) {
    doc.addPage('letter', 'portrait');
    pageNum++;
    addHeader(doc, 'Scope of Work & Next Steps', pageNum);

    let y = BODY_Y;
    if (output.scope_of_work?.length) {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text('Scope of Work', MARGIN, y);
      y += 6;
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      for (const item of output.scope_of_work) {
        const lines = doc.splitTextToSize(`• ${item}`, PORTRAIT_W - MARGIN * 2);
        doc.text(lines, MARGIN + 2, y);
        y += lines.length * 4 + 2;
        if (y > PORTRAIT_H - 30) {
          doc.addPage('letter', 'portrait');
          pageNum++;
          addHeader(doc, 'Scope of Work (cont.)', pageNum);
          y = BODY_Y;
        }
      }
    }

    if (output.next_steps?.length) {
      y += 8;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text('Next Steps', MARGIN, y);
      y += 6;
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      for (let i = 0; i < output.next_steps.length; i++) {
        doc.text(`${i + 1}. ${output.next_steps[i]}`, MARGIN + 2, y);
        y += 5;
      }
    }
    addFooter(doc);
  }

  return doc.output('blob');
}
