import type { RoomConfig } from '@/types';

export const ROOM_TEMPLATES: Record<string, RoomConfig[]> = {
  dental: [
    { name: 'Reception / Waiting', quantity: 1, area_sqft: 200 },
    { name: 'Operatory', quantity: 3, area_sqft: 120 },
    { name: 'Sterilization', quantity: 1, area_sqft: 100 },
    { name: 'X-Ray / Pano Room', quantity: 1, area_sqft: 80 },
    { name: 'Doctor\'s Office', quantity: 1, area_sqft: 120 },
    { name: 'Staff Room', quantity: 1, area_sqft: 100 },
    { name: 'Accessible Washroom', quantity: 1, area_sqft: 60 },
    { name: 'Storage / Mechanical', quantity: 1, area_sqft: 60 },
  ],
  optometry: [
    { name: 'Reception / Waiting', quantity: 1, area_sqft: 200 },
    { name: 'Pre-Test Room', quantity: 1, area_sqft: 100 },
    { name: 'Exam Room', quantity: 2, area_sqft: 120 },
    { name: 'Optical Dispensary', quantity: 1, area_sqft: 250 },
    { name: 'Contact Lens Room', quantity: 1, area_sqft: 80 },
    { name: 'Doctor\'s Office', quantity: 1, area_sqft: 120 },
    { name: 'Staff Room', quantity: 1, area_sqft: 80 },
    { name: 'Accessible Washroom', quantity: 1, area_sqft: 60 },
    { name: 'Storage', quantity: 1, area_sqft: 60 },
  ],
  veterinary: [
    { name: 'Reception / Waiting', quantity: 1, area_sqft: 250 },
    { name: 'Exam Room', quantity: 2, area_sqft: 120 },
    { name: 'Surgery Suite', quantity: 1, area_sqft: 200 },
    { name: 'Treatment Area', quantity: 1, area_sqft: 180 },
    { name: 'Kennel / Recovery', quantity: 1, area_sqft: 200 },
    { name: 'Lab / Pharmacy', quantity: 1, area_sqft: 100 },
    { name: 'X-Ray Room', quantity: 1, area_sqft: 100 },
    { name: 'Doctor\'s Office', quantity: 1, area_sqft: 100 },
    { name: 'Staff Room', quantity: 1, area_sqft: 80 },
    { name: 'Accessible Washroom', quantity: 1, area_sqft: 60 },
    { name: 'Storage / Mechanical', quantity: 1, area_sqft: 80 },
  ],
  physiotherapy: [
    { name: 'Reception / Waiting', quantity: 1, area_sqft: 200 },
    { name: 'Treatment Bay', quantity: 4, area_sqft: 80 },
    { name: 'Open Gym / Exercise Area', quantity: 1, area_sqft: 400 },
    { name: 'Private Treatment Room', quantity: 1, area_sqft: 120 },
    { name: 'Hydrotherapy Room', quantity: 1, area_sqft: 150 },
    { name: 'Staff Office', quantity: 1, area_sqft: 100 },
    { name: 'Accessible Washroom', quantity: 1, area_sqft: 60 },
    { name: 'Storage', quantity: 1, area_sqft: 60 },
  ],
  medical_office: [
    { name: 'Reception / Waiting', quantity: 1, area_sqft: 250 },
    { name: 'Exam Room', quantity: 3, area_sqft: 100 },
    { name: 'Nurse Station', quantity: 1, area_sqft: 80 },
    { name: 'Doctor\'s Office', quantity: 2, area_sqft: 120 },
    { name: 'Lab / Blood Draw', quantity: 1, area_sqft: 80 },
    { name: 'Staff Room', quantity: 1, area_sqft: 100 },
    { name: 'Accessible Washroom', quantity: 2, area_sqft: 60 },
    { name: 'Medical Records / Storage', quantity: 1, area_sqft: 80 },
  ],
  pharmacy: [
    { name: 'Retail / Dispensary Floor', quantity: 1, area_sqft: 500 },
    { name: 'Prescription Counter', quantity: 1, area_sqft: 150 },
    { name: 'Compounding Room', quantity: 1, area_sqft: 100 },
    { name: 'Consultation Room', quantity: 1, area_sqft: 80 },
    { name: 'Cold Storage', quantity: 1, area_sqft: 40 },
    { name: 'Office', quantity: 1, area_sqft: 100 },
    { name: 'Staff Area', quantity: 1, area_sqft: 80 },
    { name: 'Accessible Washroom', quantity: 1, area_sqft: 60 },
    { name: 'Storage / Receiving', quantity: 1, area_sqft: 120 },
  ],
  daycare: [
    { name: 'Reception / Entry', quantity: 1, area_sqft: 150 },
    { name: 'Infant Room', quantity: 1, area_sqft: 300 },
    { name: 'Toddler Room', quantity: 1, area_sqft: 350 },
    { name: 'Preschool Room', quantity: 1, area_sqft: 400 },
    { name: 'Nap Room', quantity: 1, area_sqft: 200 },
    { name: 'Kitchen', quantity: 1, area_sqft: 120 },
    { name: 'Children\'s Washroom', quantity: 2, area_sqft: 60 },
    { name: 'Staff Room / Office', quantity: 1, area_sqft: 100 },
    { name: 'Storage', quantity: 1, area_sqft: 80 },
  ],
  yoga_studio: [
    { name: 'Reception / Lobby', quantity: 1, area_sqft: 150 },
    { name: 'Main Studio', quantity: 1, area_sqft: 600 },
    { name: 'Secondary Studio', quantity: 1, area_sqft: 400 },
    { name: 'Change Room', quantity: 2, area_sqft: 100 },
    { name: 'Retail / Juice Bar', quantity: 1, area_sqft: 100 },
    { name: 'Office', quantity: 1, area_sqft: 80 },
    { name: 'Storage', quantity: 1, area_sqft: 60 },
  ],
  restaurant: [
    { name: 'Dining Area', quantity: 1, area_sqft: 500 },
    { name: 'Kitchen', quantity: 1, area_sqft: 300 },
    { name: 'Bar Area', quantity: 1, area_sqft: 150 },
    { name: 'Prep Area', quantity: 1, area_sqft: 100 },
    { name: 'Walk-In Cooler / Freezer', quantity: 1, area_sqft: 80 },
    { name: 'Washrooms', quantity: 2, area_sqft: 60 },
    { name: 'Office', quantity: 1, area_sqft: 60 },
    { name: 'Storage / Dry Goods', quantity: 1, area_sqft: 80 },
  ],
  retail: [
    { name: 'Sales Floor', quantity: 1, area_sqft: 600 },
    { name: 'Fitting Rooms', quantity: 2, area_sqft: 40 },
    { name: 'Checkout / POS', quantity: 1, area_sqft: 80 },
    { name: 'Back Office', quantity: 1, area_sqft: 100 },
    { name: 'Staff Room', quantity: 1, area_sqft: 60 },
    { name: 'Storage / Receiving', quantity: 1, area_sqft: 200 },
    { name: 'Accessible Washroom', quantity: 1, area_sqft: 60 },
  ],
  law_office: [
    { name: 'Reception / Waiting', quantity: 1, area_sqft: 200 },
    { name: 'Private Office', quantity: 3, area_sqft: 150 },
    { name: 'Boardroom', quantity: 1, area_sqft: 250 },
    { name: 'Open Workstations', quantity: 1, area_sqft: 200 },
    { name: 'File / Records Room', quantity: 1, area_sqft: 100 },
    { name: 'Kitchen / Staff Room', quantity: 1, area_sqft: 100 },
    { name: 'Accessible Washroom', quantity: 1, area_sqft: 60 },
    { name: 'Server / IT Room', quantity: 1, area_sqft: 40 },
  ],
  tech_office: [
    { name: 'Reception / Lobby', quantity: 1, area_sqft: 150 },
    { name: 'Open Workspace', quantity: 1, area_sqft: 400 },
    { name: 'Meeting Room', quantity: 2, area_sqft: 120 },
    { name: 'Phone Booth / Focus Room', quantity: 2, area_sqft: 40 },
    { name: 'Kitchen / Lounge', quantity: 1, area_sqft: 200 },
    { name: 'Server Room', quantity: 1, area_sqft: 60 },
    { name: 'Accessible Washroom', quantity: 1, area_sqft: 60 },
    { name: 'Storage', quantity: 1, area_sqft: 40 },
  ],
};

export function getDefaultRooms(clinicType: string): RoomConfig[] {
  return ROOM_TEMPLATES[clinicType] ?? ROOM_TEMPLATES.medical_office;
}
