ALTER TABLE projects
  ADD COLUMN IF NOT EXISTS building_type TEXT,
  ADD COLUMN IF NOT EXISTS ceiling_type TEXT DEFAULT 'tbar',
  ADD COLUMN IF NOT EXISTS soundproof BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS logo_url TEXT,
  ADD COLUMN IF NOT EXISTS inspiration_urls JSONB DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS plumbing_fixtures JSONB DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS equipment_notes TEXT;
